# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/main_window.ui'
#
# Created: Tue Apr 11 10:56:51 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 644)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(65, 123, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWaveForm = QtGui.QMenu(self.menubar)
        self.menuWaveForm.setObjectName("menuWaveForm")
        self.menuGenerate = QtGui.QMenu(self.menuWaveForm)
        self.menuGenerate.setObjectName("menuGenerate")
        self.menuMergeWith = QtGui.QMenu(self.menuWaveForm)
        self.menuMergeWith.setObjectName("menuMergeWith")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuZoom = QtGui.QMenu(self.menuView)
        self.menuZoom.setObjectName("menuZoom")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSine = QtGui.QAction(MainWindow)
        self.actionSine.setObjectName("actionSine")
        self.actionSquare = QtGui.QAction(MainWindow)
        self.actionSquare.setObjectName("actionSquare")
        self.actionTriangle = QtGui.QAction(MainWindow)
        self.actionTriangle.setObjectName("actionTriangle")
        self.actionSawtooth = QtGui.QAction(MainWindow)
        self.actionSawtooth.setObjectName("actionSawtooth")
        self.actionReverseSawtooth = QtGui.QAction(MainWindow)
        self.actionReverseSawtooth.setObjectName("actionReverseSawtooth")
        self.actionZero = QtGui.QAction(MainWindow)
        self.actionZero.setObjectName("actionZero")
        self.actionInvert = QtGui.QAction(MainWindow)
        self.actionInvert.setObjectName("actionInvert")
        self.actionMirror = QtGui.QAction(MainWindow)
        self.actionMirror.setObjectName("actionMirror")
        self.actionASMDataTable = QtGui.QAction(MainWindow)
        self.actionASMDataTable.setObjectName("actionASMDataTable")
        self.actionCDatatable = QtGui.QAction(MainWindow)
        self.actionCDatatable.setObjectName("actionCDatatable")
        self.actionMergeSine = QtGui.QAction(MainWindow)
        self.actionMergeSine.setObjectName("actionMergeSine")
        self.actionMergeSquare = QtGui.QAction(MainWindow)
        self.actionMergeSquare.setObjectName("actionMergeSquare")
        self.actionMergeTriangle = QtGui.QAction(MainWindow)
        self.actionMergeTriangle.setObjectName("actionMergeTriangle")
        self.actionMergeSawtooth = QtGui.QAction(MainWindow)
        self.actionMergeSawtooth.setObjectName("actionMergeSawtooth")
        self.actionMergeRSawtooth = QtGui.QAction(MainWindow)
        self.actionMergeRSawtooth.setObjectName("actionMergeRSawtooth")
        self.actionNormalise = QtGui.QAction(MainWindow)
        self.actionNormalise.setObjectName("actionNormalise")
        self.actionRectify = QtGui.QAction(MainWindow)
        self.actionRectify.setObjectName("actionRectify")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCentre = QtGui.QAction(MainWindow)
        self.actionCentre.setObjectName("actionCentre")
        self.actionIncrease = QtGui.QAction(MainWindow)
        self.actionIncrease.setObjectName("actionIncrease")
        self.actionDecrease = QtGui.QAction(MainWindow)
        self.actionDecrease.setObjectName("actionDecrease")
        self.actionInvert2 = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/icons/invert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInvert2.setIcon(icon)
        self.actionInvert2.setObjectName("actionInvert2")
        self.actionRectify2 = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/icons/rectify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRectify2.setIcon(icon1)
        self.actionRectify2.setObjectName("actionRectify2")
        self.actionMirror2 = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar/icons/mirror.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMirror2.setIcon(icon2)
        self.actionMirror2.setObjectName("actionMirror2")
        self.actionCentre2 = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar/icons/centre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCentre2.setIcon(icon3)
        self.actionCentre2.setObjectName("actionCentre2")
        self.actionNormalise2 = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar/icons/normalise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNormalise2.setIcon(icon4)
        self.actionNormalise2.setObjectName("actionNormalise2")
        self.actionUndo2 = QtGui.QAction(MainWindow)
        self.actionUndo2.setObjectName("actionUndo2")
        self.actionNew2 = QtGui.QAction(MainWindow)
        self.actionNew2.setObjectName("actionNew2")
        self.actionOpen2 = QtGui.QAction(MainWindow)
        self.actionOpen2.setObjectName("actionOpen2")
        self.actionSave2 = QtGui.QAction(MainWindow)
        self.actionSave2.setObjectName("actionSave2")
        self.menuExport.addAction(self.actionASMDataTable)
        self.menuExport.addAction(self.actionCDatatable)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuGenerate.addAction(self.actionSine)
        self.menuGenerate.addAction(self.actionSquare)
        self.menuGenerate.addAction(self.actionTriangle)
        self.menuGenerate.addAction(self.actionSawtooth)
        self.menuGenerate.addAction(self.actionReverseSawtooth)
        self.menuMergeWith.addAction(self.actionMergeSine)
        self.menuMergeWith.addAction(self.actionMergeSquare)
        self.menuMergeWith.addAction(self.actionMergeTriangle)
        self.menuMergeWith.addAction(self.actionMergeSawtooth)
        self.menuMergeWith.addAction(self.actionMergeRSawtooth)
        self.menuWaveForm.addAction(self.actionZero)
        self.menuWaveForm.addAction(self.menuGenerate.menuAction())
        self.menuWaveForm.addAction(self.menuMergeWith.menuAction())
        self.menuTools.addAction(self.actionInvert)
        self.menuTools.addAction(self.actionRectify)
        self.menuTools.addAction(self.actionMirror)
        self.menuTools.addAction(self.actionCentre)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionNormalise)
        self.menuEdit.addAction(self.actionUndo)
        self.menuZoom.addAction(self.actionIncrease)
        self.menuZoom.addAction(self.actionDecrease)
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWaveForm.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew2)
        self.toolBar.addAction(self.actionOpen2)
        self.toolBar.addAction(self.actionSave2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInvert2)
        self.toolBar.addAction(self.actionMirror2)
        self.toolBar.addAction(self.actionRectify2)
        self.toolBar.addAction(self.actionCentre2)
        self.toolBar.addAction(self.actionNormalise2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Wave Table Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "&Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWaveForm.setTitle(QtGui.QApplication.translate("MainWindow", "&Wave Form", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGenerate.setTitle(QtGui.QApplication.translate("MainWindow", "&Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMergeWith.setTitle(QtGui.QApplication.translate("MainWindow", "&Merge with", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuZoom.setTitle(QtGui.QApplication.translate("MainWindow", "&Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSine.setText(QtGui.QApplication.translate("MainWindow", "Sine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSine.setShortcut(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSquare.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSquare.setShortcut(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTriangle.setText(QtGui.QApplication.translate("MainWindow", "Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTriangle.setShortcut(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSawtooth.setText(QtGui.QApplication.translate("MainWindow", "Sawtooth", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSawtooth.setShortcut(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReverseSawtooth.setText(QtGui.QApplication.translate("MainWindow", "Reverse Sawtooth", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReverseSawtooth.setShortcut(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZero.setText(QtGui.QApplication.translate("MainWindow", "&Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZero.setShortcut(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert.setText(QtGui.QApplication.translate("MainWindow", "&Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirror.setText(QtGui.QApplication.translate("MainWindow", "&Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirror.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASMDataTable.setText(QtGui.QApplication.translate("MainWindow", "ASM Data table...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASMDataTable.setToolTip(QtGui.QApplication.translate("MainWindow", "Export to ASM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASMDataTable.setStatusTip(QtGui.QApplication.translate("MainWindow", "Export the wave as a data table for GCC Assember.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCDatatable.setText(QtGui.QApplication.translate("MainWindow", "C Data table...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeSine.setText(QtGui.QApplication.translate("MainWindow", "Sine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeSine.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeSquare.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeSquare.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeTriangle.setText(QtGui.QApplication.translate("MainWindow", "Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeTriangle.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeSawtooth.setText(QtGui.QApplication.translate("MainWindow", "Sawtooth", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeSawtooth.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeRSawtooth.setText(QtGui.QApplication.translate("MainWindow", "Reverse Sawtooth", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMergeRSawtooth.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalise.setText(QtGui.QApplication.translate("MainWindow", "&Normalise", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalise.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectify.setText(QtGui.QApplication.translate("MainWindow", "&Rectify", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectify.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCentre.setText(QtGui.QApplication.translate("MainWindow", "&Centre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCentre.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease.setText(QtGui.QApplication.translate("MainWindow", "&Increase", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease.setShortcut(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecrease.setText(QtGui.QApplication.translate("MainWindow", "&Decrease", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecrease.setShortcut(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert2.setText(QtGui.QApplication.translate("MainWindow", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert2.setToolTip(QtGui.QApplication.translate("MainWindow", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Invert the current waveform about the origin.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectify2.setText(QtGui.QApplication.translate("MainWindow", "Rectify", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectify2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Rectify the current waveform.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirror2.setText(QtGui.QApplication.translate("MainWindow", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirror2.setToolTip(QtGui.QApplication.translate("MainWindow", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMirror2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mirror the current waveform about the mid point of the wave.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCentre2.setText(QtGui.QApplication.translate("MainWindow", "Centre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCentre2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Centre the current waveform about the origin.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalise2.setText(QtGui.QApplication.translate("MainWindow", "Normalise", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalise2.setToolTip(QtGui.QApplication.translate("MainWindow", "Normalise", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalise2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Normalise the current waveform to fit the full dynamic range.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo2.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Undo the last action on the current waveform.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew2.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Create a new waveform.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen2.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open an exisiting waveform file.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save the current waveform.", None, QtGui.QApplication.UnicodeUTF8))

import wave_editor_rc
